// Code generated by xgen. DO NOT EDIT.

package schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlElement(required = true, name = "project")
public class Project {
	protected DecorationModel Project;
}

public class PoweredBy {
	@XmlElement(required = true, name = "logo")
	protected List<Logo> Logo;
}

public class Custom {
}

public class DecorationModel {
	@XmlAttribute(name = "name")
	protected StringAttr Name;
	@XmlElement(required = true, name = "bannerLeft")
	protected Banner BannerLeft;
	@XmlElement(required = true, name = "bannerRight")
	protected Banner BannerRight;
	@XmlElement(required = true, name = "publishDate")
	protected PublishDate PublishDate;
	@XmlElement(required = true, name = "version")
	protected Version Version;
	@XmlElement(required = true, name = "poweredBy")
	protected PoweredBy PoweredBy;
	@XmlElement(required = true, name = "skin")
	protected Skin Skin;
	@XmlElement(required = true, name = "body")
	protected Body Body;
	@XmlElement(required = true, name = "custom")
	protected Custom Custom;
}

public class Banner {
	@XmlElement(required = true, name = "name")
	protected String Name;
	@XmlElement(required = true, name = "src")
	protected String Src;
	@XmlElement(required = true, name = "alt")
	protected String Alt;
	@XmlElement(required = true, name = "href")
	protected String Href;
}

public class Head {
}

public class Links {
	@XmlElement(required = true, name = "item")
	protected List<LinkItem> Item;
}

public class Breadcrumbs {
	@XmlElement(required = true, name = "item")
	protected List<LinkItem> Item;
}

public class Body {
	@XmlElement(required = true, name = "head")
	protected Head Head;
	@XmlElement(required = true, name = "links")
	protected Links Links;
	@XmlElement(required = true, name = "breadcrumbs")
	protected Breadcrumbs Breadcrumbs;
	@XmlElement(required = true, name = "menu")
	protected List<Menu> Menu;
}

public class LinkItem {
	@XmlAttribute(name = "name")
	protected StringAttr Name;
	@XmlAttribute(name = "href")
	protected StringAttr Href;
}

public class Menu {
	@XmlAttribute(name = "name")
	protected StringAttr Name;
	@XmlAttribute(name = "inherit")
	protected StringAttr Inherit;
	@XmlAttribute(name = "inheritAsRef")
	protected BooleanAttr InheritAsRef;
	@XmlAttribute(name = "ref")
	protected StringAttr Ref;
	@XmlAttribute(name = "img")
	protected StringAttr Img;
	@XmlElement(required = true, name = "item")
	protected List<MenuItem> Item;
}

public class MenuItem {
	@XmlAttribute(name = "collapse")
	protected BooleanAttr Collapse;
	@XmlAttribute(name = "ref")
	protected StringAttr Ref;
	@XmlAttribute(name = "name")
	protected StringAttr Name;
	@XmlAttribute(name = "href")
	protected StringAttr Href;
	@XmlElement(required = true, name = "description")
	protected String Description;
	@XmlElement(required = true, name = "item")
	protected List<MenuItem> Item;
}

public class Skin {
	@XmlElement(required = true, name = "groupId")
	protected String GroupId;
	@XmlElement(required = true, name = "artifactId")
	protected String ArtifactId;
	@XmlElement(required = true, name = "version")
	protected String Version;
}

public class Version {
	@XmlAttribute(name = "position")
	protected StringAttr Position;
}

public class PublishDate {
	@XmlAttribute(name = "position")
	protected StringAttr Position;
	@XmlAttribute(name = "format")
	protected StringAttr Format;
}

public class Logo {
	@XmlAttribute(name = "img")
	protected StringAttr Img;
	@XmlAttribute(name = "name")
	protected StringAttr Name;
	@XmlAttribute(name = "href")
	protected StringAttr Href;
}
