// Code generated by xgen. DO NOT EDIT.

package schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlElement(required = true, name = "remoteResourcesBundle")
public class RemoteResourcesBundle {
	protected RemoteResourcesBundle RemoteResourcesBundle;
}

// RemoteResources is Remote resources that are contained in a remote resources bundle.
public class RemoteResources {
	@XmlElement(name = "remoteResource")
	protected List<String> RemoteResource;
}

// RemoteResourcesBundle2 is Root element of the remote-resources.xml file.
public class RemoteResourcesBundle2 {
	@XmlElement(name = "remoteResources")
	protected RemoteResources RemoteResources;
	@XmlElement(name = "sourceEncoding")
	protected String SourceEncoding;
}
