// Code generated by xgen. DO NOT EDIT.

#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_xml_rs;

use serde_xml_rs::from_reader;

#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ConditionalUintType {
	#[serde(rename = "ConditionalUintType")]
	pub boolean: bool,
	#[serde(rename = "ConditionalUintType")]
	pub unsigned_int: u32,
}
