// Code generated by xgen. DO NOT EDIT.

use serde::Serialize;
use serde::Deserialize;

use serde_xml_rs::from_reader;


// Vehicle ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Vehicle {
}


// Car ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Car {
	#[serde(flatten)]
	pub vehicle: Vehicle,
}


// Plane ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Plane {
	#[serde(flatten)]
	pub vehicle: Vehicle,
}


// transport ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct transport {
	#[serde(rename = "transport")]
	pub transport: Vehicle,
}
