// Copyright 2020 The xgen Authors. All rights reserved.
//
// DO NOT EDIT: generated by xgen XSD generator
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

typedef struct {
	char Date;
	char DateTime;
} DateSimpleType;

typedef struct {
	int PositiveInteger;
	ChoiceEnum ChoiceEnum;
} OccurrenceSimpleType;

typedef char ShortStringSimpleType;

typedef char MediumStringSimpleType;

typedef char LongStringSimpleType;

typedef char ChoiceEnum;

typedef char PropertyTypeEnum;

typedef char SetTypeEnum;

typedef char StatusEnum;

typedef char ActionTypeEnum;

typedef char PositionEnum;

typedef char OrientationEnum;

typedef char NoteTypeEnum;

typedef struct {
	char IdAttr; // attr, optional
	char NameAttr; // attr, optional
	char TemporalIdAttr; // attr, optional
	char IdentifierAttr; // attr, optional
} IdentificationGroup;

typedef struct {
	char RoleAttr; // attr, optional
	char ClassAttr; // attr, optional
	char StyleAttr; // attr, optional
} ClassificationGroup;

typedef struct {
	char NoteAttr; // attr, optional
	char AltAttr; // attr, optional
	char MetaAttr; // attr, optional
	char MiscAttr; // attr, optional
	char DraftingTipAttr; // attr, optional
	char CodificationTipAttr; // attr, optional
} AnnotationGroup;

typedef struct {
	char TitleAttr; // attr, optional
	char BriefAttr; // attr, optional
	int SortOrderAttr; // attr, optional
} DescriptionGroup;

typedef struct {
	char HrefAttr; // attr, optional
	char IdrefAttr; // attr, optional
	char PortionAttr; // attr, optional
} ReferenceGroup;

typedef struct {
	char PosAttr; // attr, optional
	char PosTextAttr; // attr, optional
	int PosCountAttr; // attr, optional
} AmendingGroup;

typedef struct {
	char SrcAttr; // attr, optional
} LinkGroup;

typedef struct {
	char ValueAttr; // attr, optional
	char StartValueAttr; // attr, optional
	char EndValueAttr; // attr, optional
} ValueGroup;

typedef struct {
	char TypeAttr; // attr, optional
	char TopicAttr; // attr, optional
} NoteGroup;

typedef struct {
	DateSimpleType DateAttr; // attr, optional
	DateSimpleType StartDateAttr; // attr, optional
	DateSimpleType EndDateAttr; // attr, optional
} DateGroup;

typedef struct {
	DateSimpleType StartPeriodAttr; // attr, optional
	DateSimpleType EndPeriodAttr; // attr, optional
	char StatusAttr; // attr, optional
	bool PartialAttr; // attr, optional
} VersioningGroup;

typedef struct {
	char TypeAttr; // attr, optional
	OccurrenceSimpleType OccurrenceAttr; // attr, optional
	DateSimpleType CommencementDateAttr; // attr, optional
} ActionGroup;

typedef struct {
	int ColspanAttr; // attr, optional
	int RowspanAttr; // attr, optional
	char LeadersAttr; // attr, optional
} CellGroup;

typedef struct {
	IdentificationGroup IdentificationGroup;
	ClassificationGroup ClassificationGroup;
	AnnotationGroup AnnotationGroup;
	VersioningGroup VersioningGroup;
} BaseType;

typedef struct {
	IdentificationGroup IdentificationGroup;
	ClassificationGroup ClassificationGroup;
	AnnotationGroup AnnotationGroup;
	VersioningGroup VersioningGroup;
} BaseBlockType;

typedef struct {
	IdentificationGroup IdentificationGroup;
	ClassificationGroup ClassificationGroup;
	AnnotationGroup AnnotationGroup;
	VersioningGroup VersioningGroup;
} BaseContentType;

typedef struct {
} MarkerType;

typedef struct {
	MarkerType Marker;
	InlineType Inline;
} InlineType;

typedef struct {
} BlockType;

typedef struct {
} TextType;

typedef struct {
	char OrientationAttr; // attr, optional
} ContentType;

typedef MarkerType Marker;

typedef InlineType Inline;

typedef BlockType Block;

typedef ContentType Content;

typedef struct {
	MetaType Meta;
	MainType Main;
	BlockType Block;
	AppendixType Appendix;
} LawDocType;

typedef struct {
	MetaType Meta;
	ContentType Content;
	AppendixType Appendix[];
} GenericDocType;

typedef struct {
	PropertyType Property;
	SetType Set;
} MetaType;

typedef struct {
	DateGroup DateGroup;
	ValueGroup ValueGroup;
	ReferenceGroup ReferenceGroup;
	char TypeAttr; // attr, optional
} PropertyType;

typedef struct {
	char TypeAttr; // attr, optional
	PropertyType Property;
	SetType Set;
} SetType;

typedef struct {
	bool GenerateAttr; // attr, optional
	HeadingStructure HeadingStructure;
	TocItemType TocItem;
	LayoutType Layout;
} TocType;

typedef struct {
	DescriptionGroup DescriptionGroup;
	HeadingStructure HeadingStructure;
	TocItemType TocItem[];
	ContentType Content[];
} TocItemType;

typedef struct {
	NoteStructure NoteStructure;
	PreambleStructure PreambleStructure;
	LevelStructure LevelStructure;
	PropertyType Property;
	BlockType Block;
	StatementType Statement;
	TocType Toc;
} MainType;

typedef struct {
	DescriptionGroup DescriptionGroup;
	MarkerType Marker;
	InlineType Inline;
	BlockType Block;
	TextType Text;
	ContentType Content;
	LevelType Level;
} StatementType;

typedef struct {
	DescriptionGroup DescriptionGroup;
	HeadingStructure HeadingStructure;
	RecitalStructure RecitalStructure[];
	StatementType EnactingFormula;
} PreambleType;

typedef struct {
	DescriptionGroup DescriptionGroup;
	NumStructure NumStructure;
	HeadingStructure HeadingStructure;
	TocStructure TocStructure[];
	LevelStructure LevelStructure;
} LevelType;

typedef struct {
	ValueGroup ValueGroup;
} NumType;

typedef struct {
} HeadingType;

typedef struct {
	RefType Ref;
	InlineType Inline;
	MarkerType Marker;
	ActionType Action[];
	LevelType Level[];
	QuotedTextType QuotedText;
	QuotedContentType QuotedContent;
} InstructionType;

typedef struct {
	ReferenceGroup ReferenceGroup;
	AmendingGroup AmendingGroup;
	ActionGroup ActionGroup;
} ActionType;

typedef struct {
	NoteGroup NoteGroup;
	HeadingType Heading;
	HeadingType Subheading[];
	NoteType Note[];
	LayoutType Layout;
} NotesType;

typedef struct {
	NoteGroup NoteGroup;
	DateGroup DateGroup;
} NoteType;

typedef struct {
	DescriptionGroup DescriptionGroup;
	LinkGroup LinkGroup;
	char OrientationAttr; // attr, optional
	NumStructure NumStructure;
	HeadingStructure HeadingStructure;
	TocStructure TocStructure;
	LevelStructure LevelStructure;
	BlockType Block;
} AppendixType;

typedef struct {
	PType P;
	SignatureType Signature[];
	LayoutType Layout;
	char Date;
} SignaturesType;

typedef struct {
} Name;

typedef struct {
} Role;

typedef struct {
} Affiliation;

typedef struct {
	Name Name;
	Role Role;
	Affiliation Affiliation;
	char Date;
} SignatureType;

typedef struct {
	AmendingGroup AmendingGroup;
} RefType;

typedef struct {
	DateGroup DateGroup;
} DateType;

typedef struct {
	char OriginAttr; // attr, optional
} QuotedTextType;

typedef struct {
	char OriginAttr; // attr, optional
} QuotedContentType;

typedef struct {
	NoteType Note;
	NotesType Notes;
} NoteStructure;

typedef struct {
	NumType Num[];
	NoteStructure NoteStructure[];
} NumStructure;

typedef struct {
	HeadingType Heading[];
	HeadingType Subheading[];
	NoteStructure NoteStructure[];
} HeadingStructure;

typedef struct {
	TocType Toc;
	NoteStructure NoteStructure[];
} TocStructure;

typedef struct {
	StatementType Statement;
	NoteStructure NoteStructure[];
} StatementStructure;

typedef struct {
	StatementType Recital;
	NoteStructure NoteStructure[];
} RecitalStructure;

typedef struct {
	PreambleType Preamble;
	StatementType EnactingFormula;
	NoteStructure NoteStructure[];
} PreambleStructure;

typedef struct {
	InstructionType Instruction[];
	ContentType Content[];
	TextType Text;
	LevelType Level;
	HeadingType CrossHeading;
	NoteStructure NoteStructure[];
	NoteStructure NoteStructure[];
	NoteStructure NoteStructure[];
} LevelStructure;

typedef LawDocType LawDoc;

typedef GenericDocType Document;

typedef MetaType Meta;

typedef PropertyType Property;

typedef SetType Set;

typedef TocType Toc;

typedef TocItemType TocItem;

typedef MainType Main;

typedef StatementType Statement;

typedef PreambleType Preamble;

typedef StatementType Recital;

typedef StatementType EnactingFormula;

typedef LevelType Level;

typedef NumType Num;

typedef TextType Text;

typedef HeadingType Heading;

typedef HeadingType Subheading;

typedef HeadingType CrossHeading;

typedef InstructionType Instruction;

typedef ActionType Action;

typedef NotesType Notes;

typedef NoteType Note;

typedef AppendixType Appendix;

typedef SignaturesType Signatures;

typedef SignatureType Signature;

typedef RefType Ref;

typedef DateType Date;

typedef QuotedTextType QuotedText;

typedef QuotedContentType QuotedContent;

typedef struct {
	char OrientationAttr; // attr, optional
	NoteStructure NoteStructure;
	RowType Header;
	RowType Row;
	TocItemType TocItem;
	BlockType Block;
	ContentType Content;
} LayoutType;

typedef struct {
	ColumnType Column[];
} RowType;

typedef struct {
	CellGroup CellGroup;
} ColumnType;

typedef struct {
} PType;

typedef struct {
} BrType;

typedef struct {
	LinkGroup LinkGroup;
	char OrientationAttr; // attr, optional
} ImgType;

typedef LayoutType Layout;

typedef RowType Header;

typedef RowType Row;

typedef ColumnType Column;

typedef PType P;

typedef BrType Br;

typedef ImgType Img;

typedef ContentType Center;

typedef ContentType FillIn;

typedef ContentType CheckBox;

typedef InlineType B;

typedef InlineType I;

typedef InlineType Sub;

typedef InlineType Sup;

typedef InlineType Del;

typedef InlineType Ins;

typedef LawDocType Bill;

typedef LawDocType Statute;

typedef LawDocType Resolution;

typedef LawDocType Amendment;

typedef LawDocType UscDoc;

typedef PropertyType DocNumber;

typedef PropertyType DocPublicationName;

typedef PropertyType DocReleasePoint;

typedef StatementType DocTitle;

typedef StatementType LongTitle;

typedef InlineType ShortTitle;

typedef InlineType Term;

typedef LevelType Preliminary;

typedef LevelType Title;

typedef LevelType Subtitle;

typedef LevelType Part;

typedef LevelType Subpart;

typedef LevelType Division;

typedef LevelType Subdivision;

typedef LevelType Chapter;

typedef LevelType Subchapter;

typedef LevelType Article;

typedef LevelType Subarticle;

typedef LevelType Section;

typedef LevelType Subsection;

typedef LevelType Paragraph;

typedef LevelType Subparagraph;

typedef LevelType Clause;

typedef LevelType Subclause;

typedef LevelType Item;

typedef LevelType Subitem;

typedef LevelType Subsubitem;

typedef TextType Def;

typedef TextType Chapeau;

typedef TextType Continuation;

typedef TextType Proviso;

typedef InstructionType AmendingFormula;

typedef NoteType SourceCredit;

typedef NoteType StatutoryNote;

typedef NoteType EditorialNote;

typedef NoteType ChangeNote;

typedef SignaturesType Made;

typedef SignaturesType Approved;

typedef AppendixType Schedule;
