// Copyright 2020 The xgen Authors. All rights reserved.
//
// DO NOT EDIT: generated by xgen XSD generator
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

typedef char Lang;

typedef char Space;

typedef char Base;

typedef char Id;

typedef struct {
	char XmlBaseAttr; // attr, optional
	char XmlLangAttr; // attr, optional
	char XmlSpaceAttr; // attr, optional
	char XmlIdAttr; // attr, optional
} SpecialAttrs;
