// Code generated by xgen. DO NOT EDIT.

// From ...
export type From = CT_Marker;

// To ...
export type To = CT_Marker;

// CT_AnchorClientData ...
export class CT_AnchorClientData {
	FLocksWithSheetAttr: boolean | null;
	FPrintsWithSheetAttr: boolean | null;
}

// CT_ShapeNonVisual ...
export class CT_ShapeNonVisual {
	CNvPr: CT_NonVisualDrawingProps;
	CNvSpPr: CT_NonVisualDrawingShapeProps;
}

// CT_Shape ...
export class CT_Shape {
	MacroAttr: string | null;
	TextlinkAttr: string | null;
	FLocksTextAttr: boolean | null;
	FPublishedAttr: boolean | null;
	NvSpPr: CT_ShapeNonVisual;
	SpPr: CT_ShapeProperties;
	Style?: CT_ShapeStyle;
	TxBody?: CT_TextBody;
}

// CT_ConnectorNonVisual ...
export class CT_ConnectorNonVisual {
	CNvPr: CT_NonVisualDrawingProps;
	CNvCxnSpPr: CT_NonVisualConnectorProperties;
}

// CT_Connector ...
export class CT_Connector {
	MacroAttr: string | null;
	FPublishedAttr: boolean | null;
	NvCxnSpPr: CT_ConnectorNonVisual;
	SpPr: CT_ShapeProperties;
	Style?: CT_ShapeStyle;
}

// CT_PictureNonVisual ...
export class CT_PictureNonVisual {
	CNvPr: CT_NonVisualDrawingProps;
	CNvPicPr: CT_NonVisualPictureProperties;
}

// CT_Picture ...
export class CT_Picture {
	MacroAttr: string | null;
	FPublishedAttr: boolean | null;
	NvPicPr: CT_PictureNonVisual;
	BlipFill: CT_BlipFillProperties;
	SpPr: CT_ShapeProperties;
	Style?: CT_ShapeStyle;
}

// CT_GraphicalObjectFrameNonVisual ...
export class CT_GraphicalObjectFrameNonVisual {
	CNvPr: CT_NonVisualDrawingProps;
	CNvGraphicFramePr: CT_NonVisualGraphicFrameProperties;
}

// CT_GraphicalObjectFrame ...
export class CT_GraphicalObjectFrame {
	MacroAttr: string | null;
	FPublishedAttr: boolean | null;
	NvGraphicFramePr: CT_GraphicalObjectFrameNonVisual;
	Xfrm: CT_Transform2D;
	AGraphic: CT_GraphicalObject;
}

// CT_GroupShapeNonVisual ...
export class CT_GroupShapeNonVisual {
	CNvPr: CT_NonVisualDrawingProps;
	CNvGrpSpPr: CT_NonVisualGroupDrawingShapeProps;
}

// CT_GroupShape ...
export class CT_GroupShape {
	NvGrpSpPr: CT_GroupShapeNonVisual;
	GrpSpPr: CT_GroupShapeProperties;
	Sp: Array<CT_Shape>;
	GrpSp: Array<CT_GroupShape>;
	GraphicFrame: Array<CT_GraphicalObjectFrame>;
	CxnSp: Array<CT_Connector>;
	Pic: Array<CT_Picture>;
}

// EG_ObjectChoices ...
export class EG_ObjectChoices {
	Sp: CT_Shape;
	GrpSp: CT_GroupShape;
	GraphicFrame: CT_GraphicalObjectFrame;
	CxnSp: CT_Connector;
	Pic: CT_Picture;
	ContentPart: CT_Rel;
}

// CT_Rel ...
export class CT_Rel {
	RIdAttr: string;
}

// ST_ColID ...
export type ST_ColID = number;

// ST_RowID ...
export type ST_RowID = number;

// CT_Marker ...
export class CT_Marker {
	Col: number;
	ColOff: ST_Coordinate;
	Row: number;
	RowOff: ST_Coordinate;
}

// ST_EditAs ...
export enum ST_EditAs {
	twoCell = 'twoCell',
	oneCell = 'oneCell',
	absolute = 'absolute',
}

// CT_TwoCellAnchor ...
export class CT_TwoCellAnchor {
	EditAsAttr: string | null;
	EG_ObjectChoices: EG_ObjectChoices;
	From: CT_Marker;
	To: CT_Marker;
	ClientData: CT_AnchorClientData;
}

// CT_OneCellAnchor ...
export class CT_OneCellAnchor {
	EG_ObjectChoices: EG_ObjectChoices;
	From: CT_Marker;
	Ext: CT_PositiveSize2D;
	ClientData: CT_AnchorClientData;
}

// CT_AbsoluteAnchor ...
export class CT_AbsoluteAnchor {
	EG_ObjectChoices: EG_ObjectChoices;
	Pos: CT_Point2D;
	Ext: CT_PositiveSize2D;
	ClientData: CT_AnchorClientData;
}

// EG_Anchor ...
export class EG_Anchor {
	TwoCellAnchor: CT_TwoCellAnchor;
	OneCellAnchor: CT_OneCellAnchor;
	AbsoluteAnchor: CT_AbsoluteAnchor;
}

// CT_Drawing ...
export class CT_Drawing {
	EG_Anchor: Array<EG_Anchor>;
}

// WsDr ...
export type WsDr = CT_Drawing;
