// Code generated by xgen. DO NOT EDIT.

// CT_Schema ...
export class CT_Schema {
	UriAttr: string | null;
	ManifestLocationAttr: string | null;
	SchemaLocationAttr: string | null;
	SchemaLanguageAttr: string | null;
}

// CT_SchemaLibrary ...
export class CT_SchemaLibrary {
	Schema: Array<CT_Schema>;
}

// SchemaLibrary ...
export type SchemaLibrary = CT_SchemaLibrary;
