// Code generated by xgen. DO NOT EDIT.

package schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

// CT_Schema ...
public class CT_Schema {
	@XmlAttribute(name = "uri")
	protected String UriAttr;
	@XmlAttribute(name = "manifestLocation")
	protected String ManifestLocationAttr;
	@XmlAttribute(name = "schemaLocation")
	protected String SchemaLocationAttr;
	@XmlAttribute(name = "schemaLanguage")
	protected String SchemaLanguageAttr;
}

// CT_SchemaLibrary ...
public class CT_SchemaLibrary {
	@XmlElement(required = true, name = "schema")
	protected List<CT_Schema> Schema;
}

@XmlAccessorType(XmlAccessType.FIELD)
@XmlElement(required = true, name = "schemaLibrary")
public class SchemaLibrary {
	protected CT_SchemaLibrary SchemaLibrary;
}
