// Code generated by xgen. DO NOT EDIT.

#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_xml_rs;

use serde_xml_rs::from_reader;


// remote_resources_bundle is Root element of the remote-resources.xml file.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct remote_resources_bundle {
	#[serde(rename = "remoteResourcesBundle")]
	pub remote_resources_bundle: RemoteResourcesBundle,
}


// RemoteResources is Remote resources that are contained in a remote resources bundle.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemoteResources {
	#[serde(rename = "remoteResource")]
	pub remote_resource: Vec<String>,
}


// RemoteResourcesBundle is Root element of the remote-resources.xml file.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct RemoteResourcesBundle {
	#[serde(rename = "remoteResources")]
	pub remote_resources: RemoteResources,
	#[serde(rename = "sourceEncoding")]
	pub source_encoding: String,
}
