// Code generated by xgen. DO NOT EDIT.

#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_xml_rs;

use serde_xml_rs::from_reader;


// toolchains is The <code>&lt;toolchains&gt;</code> element is the root of the descriptor.
//          The following table lists all of the possible child elements.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct toolchains {
	#[serde(rename = "toolchains")]
	pub toolchains: PersistedToolchains,
}


// PersistedToolchains is The toolchain instance definition.
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct PersistedToolchains {
	#[serde(rename = "toolchain")]
	pub toolchain: Vec<ToolchainModel>,
}


// Provides ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Provides {
}


// Configuration ...
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct Configuration {
}


// ToolchainModel is Type of toolchain:<ul>
//                     <li><code>jdk</code> for
//                     <a href="http://maven.apache.org/plugins/maven-toolchains-plugin/toolchains/jdk.html">JDK Standard Toolchain</a>,</li>
//                     <li>...</li>
//                     </ul>
#[derive(Debug, Deserialize, Serialize, PartialEq)]
pub struct ToolchainModel {
	#[serde(rename = "type")]
	pub type_attr: String,
	#[serde(rename = "provides")]
	pub provides: Provides,
	#[serde(rename = "configuration")]
	pub configuration: Configuration,
}
