// Copyright 2020 The xgen Authors. All rights reserved.
//
// DO NOT EDIT: generated by xgen XSD generator
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

export enum FinancialAwards {
	Pell = 'Pell',
	DLSubsidized = 'DLSubsidized',
	DLUnsubsidized = 'DLUnsubsidized',
	DLPLUS = 'DLPLUS',
	FFELSubsidized = 'FFELSubsidized',
	FFELUnsubsidized = 'FFELUnsubsidized',
	FFELPLUS = 'FFELPLUS',
	AlternativeLoan = 'AlternativeLoan',
	FWSP = 'FWSP',
	SEOG = 'SEOG',
	Perkins = 'Perkins',
	AcademicCompetitivenessGrant = 'AcademicCompetitivenessGrant',
	NationalSMARTGrant = 'NationalSMARTGrant',
	DLGraduatePLUS = 'DLGraduatePLUS',
	TEACH = 'TEACH',
	Counseling = 'Counseling',
}

export type StudentLevelCode = string;

export type SchoolNoteMessage = number;
