// Code generated by xgen. DO NOT EDIT.

export type PurchaseOrder = PurchaseOrderType;

export type Comment = string;

export class PurchaseOrderType {
	ShipTo: USAddress;
	BillTo: USAddress;
	PoComment: string;
}

export class USAddress {
	Name: string;
	Street: string;
}
