// Code generated by xgen. DO NOT EDIT.

export class PublshInformation {
	Publish_Date: Array<string>;
	Record_Count: Array<number>;
}

export class ProgramList {
	Program: Array<string>;
}

export class Id {
	Uid: Array<number>;
	IdType: Array<string>;
	IdNumber: Array<string>;
	IdCountry: Array<string>;
	IssueDate: Array<string>;
	ExpirationDate: Array<string>;
}

export class IdList {
	Id: Array<Id>;
}

export class Aka {
	Uid: Array<number>;
	Type: Array<string>;
	Category: Array<string>;
	LastName: Array<string>;
	FirstName: Array<string>;
}

export class AkaList {
	Aka: Array<Aka>;
}

export class Address {
	Uid: Array<number>;
	Address1: Array<string>;
	Address2: Array<string>;
	Address3: Array<string>;
	City: Array<string>;
	StateOrProvince: Array<string>;
	PostalCode: Array<string>;
	Country: Array<string>;
}

export class AddressList {
	Address: Array<Address>;
}

export class Nationality {
	Uid: Array<number>;
	Country: Array<string>;
	MainEntry: Array<boolean>;
}

export class NationalityList {
	Nationality: Array<Nationality>;
}

export class Citizenship {
	Uid: Array<number>;
	Country: Array<string>;
	MainEntry: Array<boolean>;
}

export class CitizenshipList {
	Citizenship: Array<Citizenship>;
}

export class DateOfBirthItem {
	Uid: Array<number>;
	DateOfBirth: Array<string>;
	MainEntry: Array<boolean>;
}

export class DateOfBirthList {
	DateOfBirthItem: Array<DateOfBirthItem>;
}

export class PlaceOfBirthItem {
	Uid: Array<number>;
	PlaceOfBirth: Array<string>;
	MainEntry: Array<boolean>;
}

export class PlaceOfBirthList {
	PlaceOfBirthItem: Array<PlaceOfBirthItem>;
}

export class VesselInfo {
	CallSign: Array<string>;
	VesselType: Array<string>;
	VesselFlag: Array<string>;
	VesselOwner: Array<string>;
	Tonnage: Array<number>;
	GrossRegisteredTonnage: Array<number>;
}

export class SdnEntry {
	Uid: Array<number>;
	FirstName: Array<string>;
	LastName: Array<string>;
	Title: Array<string>;
	SdnType: Array<string>;
	Remarks: Array<string>;
	ProgramList: Array<ProgramList>;
	IdList: Array<IdList>;
	AkaList: Array<AkaList>;
	AddressList: Array<AddressList>;
	NationalityList: Array<NationalityList>;
	CitizenshipList: Array<CitizenshipList>;
	DateOfBirthList: Array<DateOfBirthList>;
	PlaceOfBirthList: Array<PlaceOfBirthList>;
	VesselInfo: Array<VesselInfo>;
}

export class SdnList {
	PublshInformation: Array<PublshInformation>;
	SdnEntry: Array<SdnEntry>;
}
