// Copyright 2020 The xgen Authors. All rights reserved.
//
// DO NOT EDIT: generated by xgen XSD generator
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

export class CT_Schema {
	UriAttr: string | null;
	ManifestLocationAttr: string | null;
	SchemaLocationAttr: string | null;
	SchemaLanguageAttr: string | null;
}

export class CT_SchemaLibrary {
	Schema: Array<CT_Schema>;
}

export type SchemaLibrary = CT_SchemaLibrary;
