// Code generated by xgen. DO NOT EDIT.

export class CT_DatastoreSchemaRef {
	UriAttr: string;
}

export class CT_DatastoreSchemaRefs {
	SchemaRef: Array<CT_DatastoreSchemaRef>;
}

export class CT_DatastoreItem {
	ItemIDAttr: string;
	SchemaRefs: Array<CT_DatastoreSchemaRefs>;
}

export type DatastoreItem = CT_DatastoreItem;
