// Code generated by xgen. DO NOT EDIT.

package schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

public class Vehicle {
}

public class Car {
}

public class Plane {
}

@XmlAccessorType(XmlAccessType.FIELD)
@XmlElement(required = true, name = "transport")
public class Transport {
	protected Vehicle Transport;
}
