// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// CTSchema ...
type CTSchema struct {
	XMLName              xml.Name `xml:"CT_Schema"`
	UriAttr              string   `xml:"uri,attr,omitempty"`
	ManifestLocationAttr string   `xml:"manifestLocation,attr,omitempty"`
	SchemaLocationAttr   string   `xml:"schemaLocation,attr,omitempty"`
	SchemaLanguageAttr   string   `xml:"schemaLanguage,attr,omitempty"`
}

// CTSchemaLibrary ...
type CTSchemaLibrary struct {
	XMLName xml.Name    `xml:"CT_SchemaLibrary"`
	Schema  []*CTSchema `xml:"schema,omitempty"`
}

// SchemaLibrary ...
type SchemaLibrary *CTSchemaLibrary
