// Code generated by xgen. DO NOT EDIT.

typedef Component Component;

// ModuleSets ...
typedef struct {
	ModuleSet ModuleSet[];
} ModuleSets;

// FileSets ...
typedef struct {
	FileSet FileSet[];
} FileSets;

// Files ...
typedef struct {
	FileItem File[];
} Files;

// DependencySets ...
typedef struct {
	DependencySet DependencySet[];
} DependencySets;

// Repositories ...
typedef struct {
	Repository Repository[];
} Repositories;

// ContainerDescriptorHandlers ...
typedef struct {
	ContainerDescriptorHandlerConfig ContainerDescriptorHandler[];
} ContainerDescriptorHandlers;

// Component is Describes the component layout and packaging.
typedef struct {
	ModuleSets ModuleSets;
	FileSets FileSets;
	Files Files;
	DependencySets DependencySets;
	Repositories Repositories;
	ContainerDescriptorHandlers ContainerDescriptorHandlers;
} Component;

// Includes ...
typedef struct {
	char Include[];
} Includes;

// Excludes ...
typedef struct {
	char Exclude[];
} Excludes;

// DependencySet is Sets the output directory relative to the root
//             of the root directory of the assembly. For example,
//             "log" will put the specified files in the log directory,
//             directly beneath the root of the archive.
typedef struct {
	char OutputDirectory;
	Includes Includes;
	Excludes Excludes;
	char FileMode;
	char DirectoryMode;
	bool UseStrictFiltering;
	char OutputFileNameMapping;
	bool Unpack;
	UnpackOptions UnpackOptions;
	char Scope;
	bool UseProjectArtifact;
	bool UseProjectAttachments;
	bool UseTransitiveDependencies;
	bool UseTransitiveFiltering;
} DependencySet;

// UnpackOptions is Specifies options for including/excluding/filtering items extracted from an archive. (Since 2.2)
typedef struct {
	Includes Includes;
	Excludes Excludes;
	bool Filtered;
	char LineEnding;
	bool UseDefaultExcludes;
	char Encoding;
} UnpackOptions;

// Configuration ...
typedef struct {
} Configuration;

// ContainerDescriptorHandlerConfig is The handler's plexus role-hint, for lookup from the container.
typedef struct {
	char HandlerName;
	Configuration Configuration;
} ContainerDescriptorHandlerConfig;

// GroupVersionAlignments ...
typedef struct {
	GroupVersionAlignment GroupVersionAlignment[];
} GroupVersionAlignments;

// Repository is Sets the output directory relative to the root
//             of the root directory of the assembly. For example,
//             "log" will put the specified files in the log directory,
//             directly beneath the root of the archive.
typedef struct {
	char OutputDirectory;
	Includes Includes;
	Excludes Excludes;
	char FileMode;
	char DirectoryMode;
	bool IncludeMetadata;
	GroupVersionAlignments GroupVersionAlignments;
	char Scope;
} Repository;

// GroupVersionAlignment is The version you want to align this group to.
typedef struct {
	char Id;
	char Version;
	Excludes Excludes;
} GroupVersionAlignment;

// ModuleSet is If set to false, the plugin will exclude sub-modules from processing in this ModuleSet.
//           Otherwise, it will process all sub-modules, each subject to include/exclude rules.
//           Default value is true. (Since 2.2)
typedef struct {
	bool UseAllReactorProjects;
	bool IncludeSubModules;
	Includes Includes;
	Excludes Excludes;
	ModuleSources Sources;
	ModuleBinaries Binaries;
} ModuleSet;

// ModuleBinaries is Sets the output directory relative to the root
//             of the root directory of the assembly. For example,
//             "log" will put the specified files in the log directory,
//             directly beneath the root of the archive.
typedef struct {
	char OutputDirectory;
	Includes Includes;
	Excludes Excludes;
	char FileMode;
	char DirectoryMode;
	char AttachmentClassifier;
	bool IncludeDependencies;
	DependencySets DependencySets;
	bool Unpack;
	UnpackOptions UnpackOptions;
	char OutputFileNameMapping;
} ModuleBinaries;

// ModuleSources is Sets the output directory relative to the root
//             of the root directory of the assembly. For example,
//             "log" will put the specified files in the log directory.
typedef struct {
	bool UseDefaultExcludes;
	char OutputDirectory;
	Includes Includes;
	Excludes Excludes;
	char FileMode;
	char DirectoryMode;
	FileSets FileSets;
	bool IncludeModuleDirectory;
	bool ExcludeSubModuleDirectories;
	char OutputDirectoryMapping;
} ModuleSources;

// FileSet is Sets the output directory relative to the root
//             of the root directory of the assembly. For example,
//             "log" will put the specified files in the log directory.
typedef struct {
	bool UseDefaultExcludes;
	char OutputDirectory;
	Includes Includes;
	Excludes Excludes;
	char FileMode;
	char DirectoryMode;
	char Directory;
	char LineEnding;
	bool Filtered;
} FileSet;

// FileItem is Sets whether to determine if the file is filtered.
typedef struct {
	char Source;
	char OutputDirectory;
	char DestName;
	char FileMode;
	char LineEnding;
	bool Filtered;
} FileItem;
