// Code generated by xgen. DO NOT EDIT.

typedef SupplementalDataModel SupplementalDataModels;

typedef struct {
	Supplement Supplement[];
} SupplementalDataModel;

typedef struct {
} Project;

typedef struct {
	Project Project;
} Supplement;
