// Code generated by xgen. DO NOT EDIT.

package schema

// Document is Record every release with their subsequent changes.
type Document *ChangesDocument

// ChangesDocument is Contains the releases of this project with the actions taken
//             for each of the releases.
type ChangesDocument struct {
	Properties *Properties `xml:"properties"`
	Body       *Body       `xml:"body"`
}

// Body is The list of releases for this project.
type Body struct {
	Release []*Release `xml:"release"`
}

// Release is The list of actions taken for this release.
type Release struct {
	VersionAttr     *string   `xml:"version,attr"`
	DateAttr        *string   `xml:"date,attr"`
	DescriptionAttr *string   `xml:"description,attr"`
	Action          []*Action `xml:"action"`
}

// Action is A list of contibutors for this issue.
type Action struct {
	DevAttr        *string       `xml:"dev,attr"`
	DueToAttr      *string       `xml:"due-to,attr"`
	DueToEmailAttr *string       `xml:"due-to-email,attr"`
	IssueAttr      *string       `xml:"issue,attr"`
	TypeAttr       *string       `xml:"type,attr"`
	SystemAttr     *string       `xml:"system,attr"`
	DateAttr       *string       `xml:"date,attr"`
	Fixes          []*FixedIssue `xml:"fixes"`
	Dueto          []*DueTo      `xml:"dueto"`
}

// FixedIssue is A fixed issue.
type FixedIssue struct {
	IssueAttr *string `xml:"issue,attr"`
}

// DueTo is Name and Email of the person to be credited for this change. This can be used when a patch is submitted by a non-committer.
type DueTo struct {
	NameAttr  *string `xml:"name,attr"`
	EmailAttr *string `xml:"email,attr"`
}

// Properties is Page Author
type Properties struct {
	Title  *string `xml:"title"`
	Author *Author `xml:"author"`
}

// Author is A description of the author page.
type Author struct {
	EmailAttr *string `xml:"email,attr"`
}
