// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// Verifications is Root element of the verifications file.
type Verifications *Verifications

// Files is List of files and directories to check.
type Files struct {
	XMLName xml.Name `xml:"files"`
	File    []*File  `xml:"file"`
}

// Verifications is Root element of the verifications file.
type Verifications struct {
	Files *Files `xml:"files"`
}

// File is When this is set to <code>true</code> the plugin checks that the
//             file or directory exists. When set to <code>false</code> it checks
//             that the file or directory does <strong>not</strong> exist.
type File struct {
	Location string `xml:"location"`
	Contains string `xml:"contains"`
	Exists   bool   `xml:"exists"`
}
