// Code generated by xgen. DO NOT EDIT.

package schema

// Software ...
type Software struct {
	SoftwareProvider string `xml:"SoftwareProvider"`
	SoftwareVersion  string `xml:"SoftwareVersion"`
}

// TransmissionData ...
type TransmissionData struct {
	DocumentID       string      `xml:"DocumentID"`
	CreatedDateTime  string      `xml:"CreatedDateTime"`
	Software         interface{} `xml:"Software"`
	FullResponseCode string      `xml:"FullResponseCode"`
}

// CommonRecordType ...
type CommonRecordType struct {
	TransmissionData interface{} `xml:"TransmissionData"`
	Receipt          string      `xml:"Receipt"`
}
