// Copyright 2020 The xgen Authors. All rights reserved.
//
// DO NOT EDIT: generated by xgen XSD generator
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package schema

// FinancialAwards ...
type FinancialAwards string

// StudentLevelCode ...
type StudentLevelCode string

// SchoolNoteMessage ...
type SchoolNoteMessage float64
