// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// Library ...
type Library struct {
	XMLName xml.Name  `xml:"library"`
	Book    *BookType `xml:"book"`
}

// Person ...
type Person struct {
	XMLName       xml.Name `xml:"person"`
	IdAttr        string   `xml:"id,attr"`
	Name          string   `xml:"name"`
	Born          string   `xml:"born"`
	Dead          string   `xml:"dead,omitempty"`
	Qualification string   `xml:"qualification,omitempty"`
}

// Authors ...
type Authors struct {
	XMLName   xml.Name  `xml:"authors"`
	LibPerson []*Person `xml:"lib:person"`
}

// Characters ...
type Characters struct {
	XMLName   xml.Name  `xml:"characters"`
	LibPerson []*Person `xml:"lib:person"`
}

// BookType ...
type BookType struct {
	XMLName       xml.Name    `xml:"bookType"`
	IdAttr        string      `xml:"id,attr"`
	AvailableAttr string      `xml:"available,attr"`
	Isbn          string      `xml:"isbn"`
	Title         string      `xml:"title"`
	Authors       *Authors    `xml:"authors"`
	Characters    *Characters `xml:"characters"`
}
