// Code generated by xgen. DO NOT EDIT.

export type Archetyperegistry = ArchetypeRegistry;

export class Languages {
	Language: string;
}

export class FilteredExtensions {
	FilteredExtension: string;
}

export class ArchetypeRegistry {
	Languages: Languages;
	FilteredExtensions: FilteredExtensions;
}
