// Code generated by xgen. DO NOT EDIT.

// Document is Record every release with their subsequent changes.
export type Document = ChangesDocument;

// ChangesDocument is Contains the releases of this project with the actions taken
//             for each of the releases.
export class ChangesDocument {
	Properties?: Properties;
	Body?: Body;
}

// Body is The list of releases for this project.
export class Body {
	Release?: Array<Release>;
}

// Release is The list of actions taken for this release.
export class Release {
	VersionAttr?: string;
	DateAttr?: string;
	DescriptionAttr?: string;
	Action?: Array<Action>;
}

// Action is A list of contibutors for this issue.
export class Action {
	DevAttr?: string;
	DuetoAttr?: string;
	DuetoemailAttr?: string;
	IssueAttr?: string;
	TypeAttr?: string;
	SystemAttr?: string;
	DateAttr?: string;
	Fixes?: Array<FixedIssue>;
	Dueto?: Array<DueTo>;
}

// FixedIssue is A fixed issue.
export class FixedIssue {
	IssueAttr?: string;
}

// DueTo is Name and Email of the person to be credited for this change. This can be used when a patch is submitted by a non-committer.
export class DueTo {
	NameAttr?: string;
	EmailAttr?: string;
}

// Properties is Page Author
export class Properties {
	Title?: string;
	Author?: Author;
}

// Author is A description of the author page.
export class Author {
	EmailAttr?: string;
}
