// Code generated by xgen. DO NOT EDIT.

export type Component = Component;

export class FileSets {
	FileSet: Array<FileSet>;
}

export class Files {
	File: Array<FileItem>;
}

export class DependencySets {
	DependencySet: Array<DependencySet>;
}

export class Component {
	FileSets: FileSets;
	Files: Files;
	DependencySets: DependencySets;
}

export class Includes {
	Include: string;
}

export class Excludes {
	Exclude: string;
}

export class DependencySet {
	OutputFileNameMapping: string;
	Unpack: boolean;
	Scope: string;
	OutputDirectory: string;
	Includes: Includes;
	Excludes: Excludes;
	FileMode: string;
	DirectoryMode: string;
}

export class FileItem {
	Source: string;
	OutputDirectory: string;
	DestName: string;
	FileMode: string;
	LineEnding: string;
	Filtered: boolean;
}

export class FileSet {
	Directory: string;
	LineEnding: string;
	OutputDirectory: string;
	Includes: Includes;
	Excludes: Excludes;
	FileMode: string;
	DirectoryMode: string;
}
