// Code generated by xgen. DO NOT EDIT.

// ContentType is media type, as per [RFC2045]
export type ContentType = string;

// ContentTypes is comma-separated list of media types, as per [RFC2045]
export type ContentTypes = string;

// Charset is a character encoding, as per [RFC2045]
export type Charset = string;

// Charsets is a space separated list of character encodings, as per [RFC2045]
export type Charsets = string;

// LanguageCode is a language code, as per [RFC3066]
export type LanguageCode = string;

// Character is a single character, as per section 2.2 of [XML]
export type Character = string;

// Number is one or more digits
export type Number = number;

// TabindexNumber is tabindex attribute specifies the position of the current element
//       in the tabbing order for the current document. This value must be
//       a number between 0 and 32767. User agents should ignore leading zeros.
export type TabindexNumber = number;

// LinkTypes is space-separated list of link types
export type LinkTypes = Array<string>;

// MediaDesc is single or comma-separated list of media descriptors
export type MediaDesc = string;

// URI is a Uniform Resource Identifier, see [RFC2396]
export type URI = string;

// UriList is a space separated list of Uniform Resource Identifiers
export type UriList = string;

// Datetime is date and time information. ISO date format
export type Datetime = string;

// Script is script expression
export type Script = string;

// StyleSheet is style sheet data
export type StyleSheet = string;

// Text is used for titles etc.
export type Text = string;

// FrameTarget is render in this frame
export type FrameTarget = string;

// Length is nn for pixels or nn% for percentage length
export type Length = string;

// MultiLength is pixel, percentage, or relative
export type MultiLength = string;

// Pixels is integer representing length in pixels
export type Pixels = number;

// Shape ...
export enum Shape {
	rect = 'rect',
	circle = 'circle',
	poly = 'poly',
	default = 'default',
}

// Coords is comma separated list of lengths
export type Coords = string;

// ImgAlign is used for object, applet, img, input and iframe
export enum ImgAlign {
	top = 'top',
	middle = 'middle',
	bottom = 'bottom',
	left = 'left',
	right = 'right',
}

// Color is a color using sRGB: #RRGGBB as Hex values
// 
//       There are also 16 widely known color names with their sRGB values:
// 
//       Black  = #000000    Green  = #008000
//       Silver = #C0C0C0    Lime   = #00FF00
//       Gray   = #808080    Olive  = #808000
//       White  = #FFFFFF    Yellow = #FFFF00
//       Maroon = #800000    Navy   = #000080
//       Red    = #FF0000    Blue   = #0000FF
//       Purple = #800080    Teal   = #008080
//       Fuchsia= #FF00FF    Aqua   = #00FFFF
export type Color = string;

// Coreattrs is core attributes common to most elements
//       id       document-wide unique id
//       class    space separated list of classes
//       style    associated style info
//       title    advisory title/amplification
export class Coreattrs {
	IdAttr: string | null;
	ClassAttr: Array<string> | null;
	StyleAttr: string | null;
	TitleAttr: string | null;
}

// I18n is internationalization attributes
//       lang        language code (backwards compatible)
//       xml:lang    language code (as per XML 1.0 spec)
//       dir         direction for weak/neutral text
export class I18n {
	LangAttr: string | null;
	XmlLangAttr: Lang | null;
	DirAttr: string | null;
}

// Events is attributes for common UI events
//       onclick     a pointer button was clicked
//       ondblclick  a pointer button was double clicked
//       onmousedown a pointer button was pressed down
//       onmouseup   a pointer button was released
//       onmousemove a pointer was moved onto the element
//       onmouseout  a pointer was moved away from the element
//       onkeypress  a key was pressed and released
//       onkeydown   a key was pressed down
//       onkeyup     a key was released
export class Events {
	OnclickAttr: string | null;
	OndblclickAttr: string | null;
	OnmousedownAttr: string | null;
	OnmouseupAttr: string | null;
	OnmouseoverAttr: string | null;
	OnmousemoveAttr: string | null;
	OnmouseoutAttr: string | null;
	OnkeypressAttr: string | null;
	OnkeydownAttr: string | null;
	OnkeyupAttr: string | null;
}

// Focus is attributes for elements that can get the focus
//       accesskey   accessibility key character
//       tabindex    position in tabbing order
//       onfocus     the element got the focus
//       onblur      the element lost the focus
export class Focus {
	AccesskeyAttr: string | null;
	TabindexAttr: number | null;
	OnfocusAttr: string | null;
	OnblurAttr: string | null;
}

// Attrs ...
export class Attrs {
}

// TextAlign is text alignment for p, div, h1-h6. The default is
//       align="left" for ltr headings, "right" for rtl
export class TextAlign {
	AlignAttr: string | null;
}

// SpecialExtra ...
export class SpecialExtra {
	Object: Object;
	Applet: Applet;
	Img: Img;
	Map: Map;
	Iframe: Iframe;
	Source: Source;
	Macro: Macro;
}

// SpecialBasic ...
export class SpecialBasic {
	Br: Br;
	Span: Span;
	Bdo: Bdo;
}

// Special ...
export class Special {
	SpecialBasic: SpecialBasic;
	SpecialExtra: SpecialExtra;
}

// FontstyleExtra ...
export class FontstyleExtra {
	Big: Big;
	Small: Small;
	Font: Font;
	Basefont: Basefont;
}

// FontstyleBasic ...
export class FontstyleBasic {
	Tt: Tt;
	I: I;
	B: B;
	U: U;
	S: S;
	Strike: Strike;
}

// Fontstyle ...
export class Fontstyle {
	FontstyleBasic: FontstyleBasic;
	FontstyleExtra: FontstyleExtra;
}

// PhraseExtra ...
export class PhraseExtra {
	Sub: Sub;
	Sup: Sup;
}

// PhraseBasic ...
export class PhraseBasic {
	Em: Em;
	Strong: Strong;
	Dfn: Dfn;
	Code: Code;
	Q: Q;
	Samp: Samp;
	Kbd: Kbd;
	Var: Var;
	Cite: Cite;
	Abbr: Abbr;
	Acronym: Acronym;
}

// Phrase ...
export class Phrase {
	PhraseBasic: PhraseBasic;
	PhraseExtra: PhraseExtra;
}

// InlineForms ...
export class InlineForms {
	Input: Input;
	Select: Select;
	Textarea: Textarea;
	Label: Label;
	Button: Button;
}

// MiscInline ...
export class MiscInline {
	Ins: Ins;
	Del: Del;
	Script: Script;
}

// Misc ...
export class Misc {
	Noscript: Noscript;
	MiscInline: MiscInline;
}

// Inline ...
export class Inline {
	A: A;
	Special: Special;
	Fontstyle: Fontstyle;
	Phrase: Phrase;
	InlineForms: InlineForms;
}

// Inline2 is "Inline" covers inline or "text-level" element
export class Inline2 {
	Inline: Array<Inline>;
	MiscInline: Array<MiscInline>;
}

// Heading ...
export class Heading {
	H1: H1;
	H2: H2;
	H3: H3;
	H4: H4;
	H5: H5;
	H6: H6;
}

// Lists ...
export class Lists {
	Ul: Ul;
	Ol: Ol;
	Dl: Dl;
	Menu: Menu;
	Dir: Dir;
}

// Blocktext ...
export class Blocktext {
	Pre: Pre;
	Hr: Hr;
	Blockquote: Blockquote;
	Address: Address;
	Center: Center;
	Noframes: Noframes;
}

// Block ...
export class Block {
	P: P;
	Div: Div;
	Isindex: Isindex;
	Fieldset: Fieldset;
	Table: Table;
	Heading: Heading;
	Lists: Lists;
	Blocktext: Blocktext;
}

// Flow is "Flow" mixes block and inline and is used for list items etc.
export class Flow {
	Block: Array<Block>;
	Inline: Array<Inline>;
	Misc: Array<Misc>;
	Form?: Array<Form>;
}

// AContent is a elements use "Inline" excluding a
export class AContent {
	Special: Array<Special>;
	Fontstyle: Array<Fontstyle>;
	Phrase: Array<Phrase>;
	InlineForms: Array<InlineForms>;
	MiscInline: Array<MiscInline>;
}

// PreContent is pre uses "Inline" excluding img, object, applet, big, small,
//       font, or basefont
export class PreContent {
	SpecialBasic: Array<SpecialBasic>;
	FontstyleBasic: Array<FontstyleBasic>;
	PhraseBasic: Array<PhraseBasic>;
	InlineForms: Array<InlineForms>;
	MiscInline: Array<MiscInline>;
	A?: Array<A>;
}

// FormContent is form uses "Flow" excluding form
export class FormContent {
	Block: Array<Block>;
	Inline: Array<Inline>;
	Misc: Array<Misc>;
}

// ButtonContent is button uses "Flow" but excludes a, form, form controls, iframe
export class ButtonContent {
	Heading: Array<Heading>;
	Lists: Array<Lists>;
	Blocktext: Array<Blocktext>;
	Fontstyle: Array<Fontstyle>;
	Phrase: Array<Phrase>;
	Misc: Array<Misc>;
	P?: Array<P>;
	Div?: Array<Div>;
	Table?: Array<Table>;
	Br?: Array<Br>;
	Span?: Array<Span>;
	Bdo?: Array<Bdo>;
	Object?: Array<Object>;
	Applet?: Array<Applet>;
	Img?: Array<Img>;
	Map?: Array<Map>;
}

// HeadMisc ...
export class HeadMisc {
	Script: Array<Script>;
	Style: Array<Style>;
	Meta: Array<Meta>;
	Link: Array<Link>;
	Object: Array<Object>;
	Isindex: Array<Isindex>;
}

// Head is content model is "head.misc" combined with a single
//       title and an optional base element in any order
export class Head {
	I18n: I18n;
	IdAttr?: string;
	ProfileAttr?: string;
	HeadMisc: HeadMisc;
	Title?: Title;
	Base?: Base;
}

// Title is The title element is not considered part of the flow of text.
//       It should be displayed, for example as the page header or
//       window title. Exactly one title is required per document.
export class Title {
	I18n: I18n;
	IdAttr?: string;
}

// Base is document base URI
export class Base {
	IdAttr?: string;
	HrefAttr?: string;
	TargetAttr?: string;
}

// Meta is generic metainformation
export class Meta {
	I18n: I18n;
	IdAttr?: string;
	HttpequivAttr?: any;
	NameAttr?: any;
	ContentAttr: any;
	SchemeAttr?: any;
}

// Link is Relationship values can be used in principle:
// 
//       a) for document specific toolbars/menus when used
//          with the link element in document head e.g.
//            start, contents, previous, next, index, end, help
//       b) to link to a separate style sheet (rel="stylesheet")
//       c) to make a link to a script (rel="script")
//       d) by stylesheets to control how collections of
//          html nodes are rendered into printed documents
//       e) to make a link to a printable version of this document
//          e.g. a PostScript or PDF version (rel="alternate" media="print")
export class Link {
	Attrs: Attrs;
	CharsetAttr?: string;
	HrefAttr?: string;
	HreflangAttr?: string;
	TypeAttr?: string;
	RelAttr?: Array<string>;
	RevAttr?: Array<string>;
	MediaAttr?: string;
	TargetAttr?: string;
}

// Style is style info, which may include CDATA sections
export class Style {
	I18n: I18n;
	IdAttr?: string;
	TypeAttr: string;
	MediaAttr?: string;
	TitleAttr?: string;
	XmlSpaceAttr?: Space;
}

// Script2 is script statements, which may include CDATA sections
export class Script2 {
	IdAttr?: string;
	CharsetAttr?: string;
	TypeAttr: string;
	LanguageAttr?: any;
	SrcAttr?: string;
	DeferAttr?: string;
	XmlSpaceAttr?: Space;
}

// Noscript is alternate content container for non script-based rendering
export class Noscript extends Flow  {
	Attrs: Attrs;
}

// Iframe is inline subwindow
export class Iframe extends Flow  {
	Coreattrs: Coreattrs;
	LongdescAttr?: string;
	NameAttr?: string;
	SrcAttr?: string;
	FrameborderAttr?: string;
	MarginwidthAttr?: number;
	MarginheightAttr?: number;
	ScrollingAttr?: string;
	AlignAttr?: string;
	HeightAttr?: string;
	WidthAttr?: string;
}

// Noframes is alternate content container for non frame-based rendering
export class Noframes extends Flow  {
	Attrs: Attrs;
}

// Div is generic language/style container
export class Div extends Flow  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// P ...
export class P extends Inline  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// H1 ...
export class H1 extends Inline  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// H2 ...
export class H2 extends Inline  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// H3 ...
export class H3 extends Inline  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// H4 ...
export class H4 extends Inline  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// H5 ...
export class H5 extends Inline  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// H6 ...
export class H6 extends Inline  {
	Attrs: Attrs;
	TextAlign: TextAlign;
}

// ULStyle is Unordered list bullet styles
export enum ULStyle {
	disc = 'disc',
	square = 'square',
	circle = 'circle',
}

// Ul is Unordered list
export class Ul {
	Attrs: Attrs;
	TypeAttr?: string;
	CompactAttr?: string;
	Li: Array<Li>;
}

// OLStyle is Ordered list numbering style
// 
//       1   arabic numbers      1, 2, 3, ...
//       a   lower alpha         a, b, c, ...
//       A   upper alpha         A, B, C, ...
//       i   lower roman         i, ii, iii, ...
//       I   upper roman         I, II, III, ...
// 
//       The style is applied to the sequence number which by default
//       is reset to 1 for the first list item in an ordered list.
export type OLStyle = string;

// Ol is Ordered (numbered) list
export class Ol {
	Attrs: Attrs;
	TypeAttr?: string;
	CompactAttr?: string;
	StartAttr?: number;
	Li: Array<Li>;
}

// Menu is single column list (DEPRECATED)
export class Menu {
	Attrs: Attrs;
	CompactAttr?: string;
	Li: Array<Li>;
}

// Dir is multiple column list (DEPRECATED)
export class Dir {
	Attrs: Attrs;
	CompactAttr?: string;
	Li: Array<Li>;
}

// LIStyle is LIStyle is constrained to: "(ULStyle|OLStyle)"
export type LIStyle = string;

// Li is list item
export class Li extends Flow  {
	Attrs: Attrs;
	TypeAttr?: string;
	ValueAttr?: number;
}

// Dl ...
export class Dl {
	Attrs: Attrs;
	CompactAttr?: string;
	Dt?: Array<Dt>;
	Dd?: Array<Dd>;
}

// Dt ...
export class Dt extends Inline  {
	Attrs: Attrs;
}

// Dd ...
export class Dd extends Flow  {
	Attrs: Attrs;
}

// Address is information on author
export class Address {
	Attrs: Attrs;
	Inline: Array<Inline>;
	MiscInline: Array<MiscInline>;
	P?: Array<P>;
}

// Hr ...
export class Hr {
	Attrs: Attrs;
	AlignAttr?: string;
	NoshadeAttr?: string;
	SizeAttr?: number;
	WidthAttr?: string;
}

// Pre is content is "Inline" excluding
//          "img|object|applet|big|small|sub|sup|font|basefont"
export class Pre extends PreContent  {
	Attrs: Attrs;
	WidthAttr?: number;
	XmlSpaceAttr?: Space;
}

// Blockquote ...
export class Blockquote extends Flow  {
	Attrs: Attrs;
	CiteAttr?: string;
}

// Center is center content
export class Center extends Flow  {
	Attrs: Attrs;
}

// Ins ...
export class Ins extends Flow  {
	Attrs: Attrs;
	CiteAttr?: string;
	DatetimeAttr?: string;
}

// Del ...
export class Del extends Flow  {
	Attrs: Attrs;
	CiteAttr?: string;
	DatetimeAttr?: string;
}

// A is content is "Inline" except that anchors shouldn't be nested
export class A extends AContent  {
	Attrs: Attrs;
	Focus: Focus;
	CharsetAttr?: string;
	TypeAttr?: string;
	NameAttr?: string;
	HrefAttr?: string;
	HreflangAttr?: string;
	RelAttr?: Array<string>;
	RevAttr?: Array<string>;
	ShapeAttr?: string;
	CoordsAttr?: string;
	TargetAttr?: string;
}

// Span is generic language/style container
export class Span extends Inline  {
	Attrs: Attrs;
}

// Bdo is I18N BiDi over-ride
export class Bdo extends Inline  {
	Coreattrs: Coreattrs;
	Events: Events;
	LangAttr?: string;
	XmlLangAttr?: Lang;
	DirAttr: string;
}

// Br is forced line break
export class Br {
	Coreattrs: Coreattrs;
	ClearAttr?: string;
}

// Em is emphasis
export class Em extends Inline  {
	Attrs: Attrs;
}

// Strong is strong emphasis
export class Strong extends Inline  {
	Attrs: Attrs;
}

// Dfn is definitional
export class Dfn extends Inline  {
	Attrs: Attrs;
}

// Code is program code
export class Code extends Inline  {
	Attrs: Attrs;
}

// Samp is sample
export class Samp extends Inline  {
	Attrs: Attrs;
}

// Kbd is something user would type
export class Kbd extends Inline  {
	Attrs: Attrs;
}

// Var is variable
export class Var extends Inline  {
	Attrs: Attrs;
}

// Cite is citation
export class Cite extends Inline  {
	Attrs: Attrs;
}

// Abbr is abbreviation
export class Abbr extends Inline  {
	Attrs: Attrs;
}

// Acronym is acronym
export class Acronym extends Inline  {
	Attrs: Attrs;
}

// Q is inlined quote
export class Q extends Inline  {
	Attrs: Attrs;
	CiteAttr?: string;
}

// Sub is subscript
export class Sub extends Inline  {
	Attrs: Attrs;
}

// Sup is superscript
export class Sup extends Inline  {
	Attrs: Attrs;
}

// Tt is fixed pitch font
export class Tt extends Inline  {
	Attrs: Attrs;
}

// I is italic font
export class I extends Inline  {
	Attrs: Attrs;
}

// B is bold font
export class B extends Inline  {
	Attrs: Attrs;
}

// Big is bigger font
export class Big extends Inline  {
	Attrs: Attrs;
}

// Small is smaller font
export class Small extends Inline  {
	Attrs: Attrs;
}

// U is underline
export class U extends Inline  {
	Attrs: Attrs;
}

// S is strike-through
export class S extends Inline  {
	Attrs: Attrs;
}

// Strike is strike-through
export class Strike extends Inline  {
	Attrs: Attrs;
}

// Basefont is base font size
export class Basefont {
	IdAttr?: string;
	SizeAttr: any;
	ColorAttr?: string;
	FaceAttr?: any;
}

// Font is local change to font
export class Font extends Inline  {
	Coreattrs: Coreattrs;
	I18n: I18n;
	SizeAttr?: any;
	ColorAttr?: string;
	FaceAttr?: any;
}

// Object ...
export class Object {
	Attrs: Attrs;
	DeclareAttr?: string;
	ClassidAttr?: string;
	CodebaseAttr?: string;
	DataAttr?: string;
	TypeAttr?: string;
	CodetypeAttr?: string;
	ArchiveAttr?: string;
	StandbyAttr?: string;
	HeightAttr?: string;
	WidthAttr?: string;
	UsemapAttr?: string;
	NameAttr?: string;
	TabindexAttr?: number;
	AlignAttr?: string;
	BorderAttr?: number;
	HspaceAttr?: number;
	VspaceAttr?: number;
	Block: Array<Block>;
	Inline: Array<Inline>;
	Misc: Array<Misc>;
	Param?: Array<Param>;
	Form?: Array<Form>;
}

// Param is param is used to supply a named property value.
//       In XML it would seem natural to follow RDF and support an
//       abbreviated syntax where the param elements are replaced
//       by attribute value pairs on the object start tag.
export class Param {
	IdAttr?: string;
	NameAttr: any;
	ValueAttr?: any;
	ValuetypeAttr?: string;
	TypeAttr?: string;
}

// Applet ...
export class Applet {
	Coreattrs: Coreattrs;
	CodebaseAttr?: string;
	ArchiveAttr?: any;
	CodeAttr?: any;
	ObjectAttr?: any;
	AltAttr?: string;
	NameAttr?: string;
	WidthAttr: string;
	HeightAttr: string;
	AlignAttr?: string;
	HspaceAttr?: number;
	VspaceAttr?: number;
	Block: Array<Block>;
	Inline: Array<Inline>;
	Misc: Array<Misc>;
	Param?: Array<Param>;
	Form?: Array<Form>;
}

// Img ...
export class Img {
	Attrs: Attrs;
	SrcAttr: string;
	AltAttr: string;
	NameAttr?: string;
	LongdescAttr?: string;
	HeightAttr?: string;
	WidthAttr?: string;
	UsemapAttr?: string;
	IsmapAttr?: string;
	AlignAttr?: string;
	BorderAttr?: string;
	HspaceAttr?: number;
	VspaceAttr?: number;
}

// Map ...
export class Map {
	I18n: I18n;
	Events: Events;
	IdAttr: string;
	ClassAttr?: any;
	StyleAttr?: string;
	TitleAttr?: string;
	NameAttr?: any;
	Block: Array<Block>;
	Misc: Array<Misc>;
	Form?: Array<Form>;
	Area?: Array<Area>;
}

// Area ...
export class Area {
	Attrs: Attrs;
	Focus: Focus;
	ShapeAttr?: string;
	CoordsAttr?: string;
	HrefAttr?: string;
	NohrefAttr?: string;
	AltAttr: string;
	TargetAttr?: string;
}

// Form ...
export class Form extends FormContent  {
	Attrs: Attrs;
	ActionAttr: string;
	MethodAttr?: string;
	EnctypeAttr?: string;
	OnsubmitAttr?: string;
	OnresetAttr?: string;
	AcceptAttr?: string;
	AcceptcharsetAttr?: string;
	TargetAttr?: string;
}

// Label is Each label must not contain more than ONE field
//       Label elements shouldn't be nested.
export class Label extends Inline  {
	Attrs: Attrs;
	ForAttr?: string;
	AccesskeyAttr?: string;
	OnfocusAttr?: string;
	OnblurAttr?: string;
}

// InputType ...
export enum InputType {
	text = 'text',
	password = 'password',
	checkbox = 'checkbox',
	radio = 'radio',
	submit = 'submit',
	reset = 'reset',
	file = 'file',
	hidden = 'hidden',
	image = 'image',
	button = 'button',
}

// Input is form control
export class Input {
	Attrs: Attrs;
	Focus: Focus;
	TypeAttr?: string;
	NameAttr?: any;
	ValueAttr?: any;
	CheckedAttr?: string;
	DisabledAttr?: string;
	ReadonlyAttr?: string;
	SizeAttr?: any;
	MaxlengthAttr?: number;
	SrcAttr?: string;
	AltAttr?: any;
	UsemapAttr?: string;
	OnselectAttr?: string;
	OnchangeAttr?: string;
	AcceptAttr?: string;
	AlignAttr?: string;
}

// Select is option selector
export class Select {
	Attrs: Attrs;
	NameAttr?: any;
	SizeAttr?: number;
	MultipleAttr?: string;
	DisabledAttr?: string;
	TabindexAttr?: number;
	OnfocusAttr?: string;
	OnblurAttr?: string;
	OnchangeAttr?: string;
	Optgroup?: Array<Optgroup>;
	Option?: Array<Option>;
}

// Optgroup is option group
export class Optgroup {
	Attrs: Attrs;
	DisabledAttr?: string;
	LabelAttr: string;
	Option: Array<Option>;
}

// Option is selectable choice
export class Option {
	Attrs: Attrs;
	SelectedAttr?: string;
	DisabledAttr?: string;
	LabelAttr?: string;
	ValueAttr?: any;
}

// Textarea is multi-line text field
export class Textarea {
	Attrs: Attrs;
	Focus: Focus;
	NameAttr?: any;
	RowsAttr: number;
	ColsAttr: number;
	DisabledAttr?: string;
	ReadonlyAttr?: string;
	OnselectAttr?: string;
	OnchangeAttr?: string;
}

// Fieldset is The fieldset element is used to group form fields.
//       Only one legend element should occur in the content
//       and if present should only be preceded by whitespace.
// 
//       NOTE: this content model is different from the XHTML 1.0 DTD,
//       closer to the intended content model in HTML4 DTD
export class Fieldset {
	Attrs: Attrs;
	Block: Array<Block>;
	Inline: Array<Inline>;
	Misc: Array<Misc>;
	Legend: Legend;
	Form?: Array<Form>;
}

// LAlign ...
export enum LAlign {
	top = 'top',
	bottom = 'bottom',
	left = 'left',
	right = 'right',
}

// Legend is fieldset label
export class Legend extends Inline  {
	Attrs: Attrs;
	AccesskeyAttr?: string;
	AlignAttr?: string;
}

// Button is Content is "Flow" excluding a, form and form controls
export class Button extends ButtonContent  {
	Attrs: Attrs;
	Focus: Focus;
	NameAttr?: any;
	ValueAttr?: any;
	TypeAttr?: string;
	DisabledAttr?: string;
}

// Isindex is single-line text input control (DEPRECATED)
export class Isindex {
	Coreattrs: Coreattrs;
	I18n: I18n;
	PromptAttr?: string;
}

// TFrame is The border attribute sets the thickness of the frame around the
//       table. The default units are screen pixels.
// 
//       The frame attribute specifies which parts of the frame around
//       the table should be rendered. The values are not the same as
//       CALS to avoid a name clash with the valign attribute.
export enum TFrame {
	void = 'void',
	above = 'above',
	below = 'below',
	hsides = 'hsides',
	lhs = 'lhs',
	rhs = 'rhs',
	vsides = 'vsides',
	box = 'box',
	border = 'border',
}

// TRules is The rules attribute defines which rules to draw between cells:
// 
//       If rules is absent then assume:
//           "none" if border is absent or border="0" otherwise "all"
export enum TRules {
	none = 'none',
	groups = 'groups',
	rows = 'rows',
	cols = 'cols',
	all = 'all',
}

// TAlign is horizontal placement of table relative to document
export enum TAlign {
	left = 'left',
	center = 'center',
	right = 'right',
}

// Cellhalign is horizontal alignment attributes for cell contents
// 
//       char        alignment char, e.g. char=':'
//       charoff     offset for alignment char
export class Cellhalign {
	AlignAttr: string | null;
	CharAttr: string | null;
	CharoffAttr: string | null;
}

// Cellvalign is vertical alignment attributes for cell contents
export class Cellvalign {
	ValignAttr: string | null;
}

// Table ...
export class Table {
	Attrs: Attrs;
	SummaryAttr?: string;
	WidthAttr?: string;
	BorderAttr?: number;
	FrameAttr?: string;
	RulesAttr?: string;
	CellspacingAttr?: string;
	CellpaddingAttr?: string;
	AlignAttr?: string;
	BgcolorAttr?: string;
	Caption?: Caption;
	Col?: Array<Col>;
	Colgroup?: Array<Colgroup>;
	Thead?: Thead;
	Tfoot?: Tfoot;
	Tbody?: Array<Tbody>;
	Tr?: Array<Tr>;
}

// CAlign ...
export enum CAlign {
	top = 'top',
	bottom = 'bottom',
	left = 'left',
	right = 'right',
}

// Caption ...
export class Caption extends Inline  {
	Attrs: Attrs;
	AlignAttr?: string;
}

// Thead ...
export class Thead {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	Tr: Array<Tr>;
}

// Tfoot ...
export class Tfoot {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	Tr: Array<Tr>;
}

// Tbody ...
export class Tbody {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	Tr: Array<Tr>;
}

// Colgroup is colgroup groups a set of col elements. It allows you to group
//       several semantically related columns together.
export class Colgroup {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	SpanAttr?: number;
	WidthAttr?: string;
	Col?: Array<Col>;
}

// Col is col elements define the alignment properties for cells in
//       one or more columns.
// 
//       The width attribute specifies the width of the columns, e.g.
// 
//           width=64        width in screen pixels
//           width=0.5*      relative width of 0.5
// 
//       The span attribute causes the attributes of one
//       col element to apply to more than one column.
export class Col {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	SpanAttr?: number;
	WidthAttr?: string;
}

// Tr ...
export class Tr {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	BgcolorAttr?: string;
	Th?: Array<Th>;
	Td?: Array<Td>;
}

// Scope is Scope is simpler than headers attribute for common tables
export enum Scope {
	row = 'row',
	col = 'col',
	rowgroup = 'rowgroup',
	colgroup = 'colgroup',
}

// Th ...
export class Th extends Flow  {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	AbbrAttr?: string;
	AxisAttr?: any;
	HeadersAttr?: Array<string>;
	ScopeAttr?: string;
	RowspanAttr?: number;
	ColspanAttr?: number;
	NowrapAttr?: string;
	BgcolorAttr?: string;
	WidthAttr?: string;
	HeightAttr?: string;
}

// Td ...
export class Td extends Flow  {
	Attrs: Attrs;
	Cellhalign: Cellhalign;
	Cellvalign: Cellvalign;
	AbbrAttr?: string;
	AxisAttr?: any;
	HeadersAttr?: Array<string>;
	ScopeAttr?: string;
	RowspanAttr?: number;
	ColspanAttr?: number;
	NowrapAttr?: string;
	BgcolorAttr?: string;
	WidthAttr?: string;
	HeightAttr?: string;
}

// Faqs is Required part element for this faqs element.
export class Faqs {
	I18n: I18n;
	IdAttr?: string;
	TitleAttr?: string;
	ToplinkAttr?: boolean;
	Part: Array<Part>;
}

// Part is Required faq element for this part element.
export class Part {
	IdAttr?: string;
	Title?: Title;
	Faq: Array<Faq>;
}

// Faq is The answer of this faq element.
export class Faq {
	IdAttr?: string;
	Question: Question;
	Answer: Answer;
}

// Question is A faq question element.
export class Question {
	Fontstyle: Array<Fontstyle>;
	Phrase: Array<Phrase>;
}

// Answer is A faq answer element.
export class Answer {
	Block: Array<Block>;
	Inline: Array<Inline>;
	Misc: Array<Misc>;
	Form?: Array<Form>;
}

// Source is A source element.
export class Source {
}

// Macro is A macro element.
export class Macro {
	NameAttr: string;
	Param?: Array<Param>;
}
