// Code generated by xgen. DO NOT EDIT.

export type ProfilesXml = ProfilesRoot;

export class Profiles {
	Profile: Array<Profile>;
}

export class ActiveProfiles {
	ActiveProfile: string;
}

export class ProfilesRoot {
	Profiles: Profiles;
	ActiveProfiles: ActiveProfiles;
}

export class Properties {
}

export class Repositories {
	Repository: Array<Repository>;
}

export class PluginRepositories {
	PluginRepository: Array<Repository>;
}

export class Profile {
	Id: string;
	Activation: Activation;
	Properties: Properties;
	Repositories: Repositories;
	PluginRepositories: PluginRepositories;
}

export class Activation {
	ActiveByDefault: boolean;
	Jdk: string;
	Os: ActivationOS;
	Property: ActivationProperty;
	File: ActivationFile;
}

export class ActivationOS {
	Name: string;
	Family: string;
	Arch: string;
	Version: string;
}

export class ActivationProperty {
	Name: string;
	Value: string;
}

export class ActivationFile {
	Missing: string;
	Exists: string;
}

export class Repository {
	Releases: RepositoryPolicy;
	Snapshots: RepositoryPolicy;
	Id: string;
	Name: string;
	Url: string;
	Layout: string;
}

export class RepositoryPolicy {
	Enabled: boolean;
	UpdatePolicy: string;
	ChecksumPolicy: string;
}
