// Code generated by xgen. DO NOT EDIT.

export type RemoteResourcesBundle = RemoteResourcesBundle;

export class RemoteResources {
	RemoteResource: string;
}

export class RemoteResourcesBundle {
	RemoteResources: RemoteResources;
	SourceEncoding: string;
}
